# Generated by Django 2.0.7 on 2018-08-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_order_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed_date',
            field=models.DateTimeField(null=True),
        ),
    ]
