# Generated by Django 2.0.7 on 2018-07-26 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_toppings', models.PositiveSmallIntegerField()),
                ('max_toppings', models.PositiveSmallIntegerField()),
                ('topping_price_is_included', models.BooleanField(verbose_name='Prices for toppings are included in the price of the dish')),
            ],
        ),
        migrations.CreateModel(
            name='MenuSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('med', 'Medium'), ('sm', 'Small'), ('lg', 'Large')], max_length=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='menu_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.MenuSection'),
        ),
        migrations.AddField(
            model_name='dish',
            name='sizes',
            field=models.ManyToManyField(to='orders.Size'),
        ),
        migrations.AddField(
            model_name='dish',
            name='toppings',
            field=models.ManyToManyField(to='orders.Topping'),
        ),
    ]
