# Generated by Django 2.0.7 on 2018-07-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='name',
            field=models.CharField(default='food', max_length=30),
            preserve_default=False,
        ),
    ]
