# Generated by Django 2.0.7 on 2018-07-26 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_dish_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='menu_section',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='orders.MenuSection'),
            preserve_default=False,
        ),
    ]
