# Generated by Django 2.0.7 on 2018-07-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_topping_menu_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='sizes',
        ),
        migrations.AddField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='price_large',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Large size price'),
        ),
        migrations.AddField(
            model_name='dish',
            name='price_small',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Small size price'),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
