# Generated by Django 2.0.7 on 2018-07-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180726_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price_large',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Large size price'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price_small',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Small size price'),
        ),
    ]
