# Generated by Django 2.0.7 on 2018-07-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180726_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='toppings',
            field=models.ManyToManyField(to='orders.Topping'),
        ),
    ]
