# Generated by Django 2.0.7 on 2018-07-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180726_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='topping_price_is_included',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='toppings',
        ),
        migrations.AddField(
            model_name='menusection',
            name='topping_price_is_included',
            field=models.BooleanField(default=True, verbose_name='Prices for toppings are included in the price of the dish'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menusection',
            name='toppings',
            field=models.ManyToManyField(to='orders.Topping'),
        ),
    ]
