# Generated by Django 2.0.7 on 2018-07-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20180726_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='menu_section',
        ),
        migrations.AddField(
            model_name='topping',
            name='menu_sections',
            field=models.ManyToManyField(blank=True, null=True, to='orders.MenuSection'),
        ),
    ]
