# Generated by Django 2.0.7 on 2018-07-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20180726_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='menu_sections',
            field=models.ManyToManyField(blank=True, to='orders.MenuSection'),
        ),
    ]
