# Generated by Django 2.0.7 on 2018-07-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20180726_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menusection',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='orders.Topping'),
        ),
    ]
