# Generated by Django 2.0.7 on 2018-07-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20180727_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='menusection',
            name='dishes',
            field=models.ManyToManyField(blank=True, to='orders.Dish'),
        ),
    ]
