# Generated by Django 2.0.7 on 2018-07-28 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_menusection_dishes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menusection',
            old_name='toppings',
            new_name='available_toppings',
        ),
    ]
