# Generated by Django 2.0.7 on 2018-07-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20180728_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menusection',
            name='available_toppings',
            field=models.ManyToManyField(blank=True, related_name='available_toppings', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='menusection',
            name='toppings_included',
            field=models.ManyToManyField(blank=True, related_name='toppings_included', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='topping',
            name='menu_sections',
            field=models.ManyToManyField(blank=True, related_name='menu_sections', to='orders.MenuSection'),
        ),
    ]
