# Generated by Django 2.0.7 on 2018-07-28 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20180728_0209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menusection',
            old_name='dishes',
            new_name='dishes_included',
        ),
    ]
