# Generated by Django 2.0.7 on 2018-07-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('large', 'Large'), ('regular', 'Regular')], max_length=10),
        ),
    ]
