# Generated by Django 2.0.7 on 2018-07-29 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20180728_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='max_toppings',
            new_name='max_global_toppings',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='min_toppings',
            new_name='min_global_toppings',
        ),
    ]
