# Generated by Django 2.0.7 on 2018-07-29 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20180729_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='menu_sections',
        ),
    ]
