# Generated by Django 2.0.7 on 2018-07-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_remove_topping_menu_sections'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menusection',
            old_name='available_toppings',
            new_name='global_available_toppings',
        ),
        migrations.AddField(
            model_name='dish',
            name='local_available_toppings',
            field=models.ManyToManyField(blank=True, to='orders.Topping'),
        ),
    ]
