# Generated by Django 2.0.7 on 2018-07-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20180729_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='toppings',
        ),
        migrations.AddField(
            model_name='item',
            name='selected_global_toppings',
            field=models.ManyToManyField(blank=True, related_name='selected_global_toppings', to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='item',
            name='selected_local_toppings',
            field=models.ManyToManyField(blank=True, related_name='selected_local_toppings', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(max_length=10),
        ),
    ]
