# Generated by Django 2.0.7 on 2018-07-29 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20180729_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='selected_global_toppings',
        ),
        migrations.RemoveField(
            model_name='item',
            name='selected_local_toppings',
        ),
        migrations.AddField(
            model_name='item',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='orders.Topping'),
        ),
    ]
