# Generated by Django 2.0.7 on 2018-07-30 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20180729_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menusection',
            name='dishes_included',
        ),
    ]
