# Generated by Django 2.0.7 on 2018-07-30 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180730_2118'),
        ('orders', '0026_remove_menusection_dishes_included'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='item',
            name='toppings',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
